### ISSUE TITLE
Arquivos

### ISSUE THREAD

**Issue by cajubavictor** [RenanGaleno/jogodaforca#2]
Não entendi como tu fez a comunicação com os outros arquivos do código?

**Comment by RenanGaleno** [comment]
Bom, as wordlists são carregadas com as funções de manipulação de arquivos padrões da linguagem. Se tiver falando dos includes, são bibliotecas da linguagem inclusas na maioria dos SOs, à exceção da curses.h que o Windows não trás, mas que eu incluí como DLL.
